spring.datasource.url=jdbc:mysql://smartrdv-uca-5230.i.aivencloud.com:28865/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_KnIn-Q6sJwDbQXfaFO4

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8081
server.error.include-message=always
